### ISSUE TITLE
Feature Request: Markdown Extra

### ISSUE THREAD

**Issue by bobrocke** [jonschlinkert/sublime-markdown-extended#100]
I'd like to see support for the Markdown Extra syntax added:

https://michelf.ca/projects/php-markdown/extra/

**Comment by jonschlinkert** [comment]
I think going forward, it's probably best for us to only implement features that are in the [commonmark](http://commonmark.org/) specification. thanks for caring enough to create the request, I do appreciate it. if you find any specific features that markdown extra has that also are in the commonmark specification, please feel free to create another feature request.
