### ISSUE TITLE
Drag links from browser and format

### ISSUE THREAD

**Issue by khalidl** [jonschlinkert/sublime-markdown-extended#103]
Not so much an issue, but more of a request:

Was wondering if urls and links dragged from a browser — address-bar or from the page — into a document can be formatted as a Markdown link. The dragged link would automatically be formatted in the following way:  
`[Google](http://www.google.com)`

Not sure if this is possible. Both Byword and iA Writer have this functionality, and it would be great if this was also possible with Markdown Extended.

Thanks!

**Comment by jonschlinkert** [comment]
You might be able to accomplish this with a ST plugin, but it's outside of the scope of what this package does. I do appreciate the request though. thank you
