### ISSUE TITLE
Support some Latex syntax to highlight

### ISSUE THREAD

**Issue by hadim** [jonschlinkert/sublime-markdown-extended#105]
Following #19.

It would be nice to have some latex commands supported for color syntaxing.

Indeed one of the software which make me use markdown a lot is pandoc (and I am sure I am not alone here...). And pandoc allows raw LaTex commands.

Could you at least add syntax and color features for these things:

- math equations which can take two forms : `$ inline equation $` or `$$ multiline equation $$`
- bibliography key reference such as `[@my_bib_key]`
- sometime I write `_` in a command (math equations for exemple) and markdown-extended think I am starting a bold string... which ruins the whole following syntax (hope I am clear).

**Comment by saikon** [comment]
I agree that ignoring or formatting stuff inside dollar signs would make things cleaner.

With the current system equations get messy:
![image](https://cloud.githubusercontent.com/assets/4550179/10658576/f6614788-78a0-11e5-8872-8c2ed4b23798.png)

Something like regular LaTeX highlighting (which just colors everything with one color between dollar signs) would be more than enough for me:
![image](https://cloud.githubusercontent.com/assets/4550179/10658597/1b405738-78a1-11e5-8253-b27f28fc5b55.png)
