### ISSUE TITLE
`case` keyword issue

### ISSUE THREAD

**Issue by szhu** [jonschlinkert/sublime-markdown-extended#118]
<img width="706" alt="screen shot 2016-02-14 at 5 10 42 pm" src="https://cloud.githubusercontent.com/assets/1570168/13037821/e6e66aac-d33d-11e5-90fa-3b3bbbee988f.png">

**Comment by SuperPaintman** [comment]
The shell comments begin with `#`

**Comment by SuperPaintman** [comment]
```sh
$ gulp dev # start a dev server
```

**Comment by jonschlinkert** [comment]
right, in ST 3013 some changes were made that makes highlighting less tolerant of errors. whenever you see this happen, it's probably because there is a syntax error in your example

**Comment by szhu** [comment]
Ah dammit it took me a while to realize what you were talking about. Thanks for pointing that out! Mistake not mine btw :)

Also, I'd imagine that while stricter syntax highlighting would be bad for cases like this, it probably leads to less discrepancies between the syntax highlighting and actual parsers, so I reluctantly welcome this change.
