### ISSUE TITLE
Pandoc YAML Syntax

### ISSUE THREAD

**Issue by vladipus** [jonschlinkert/sublime-markdown-extended#128]
According to Pandoc's [documentation](http://pandoc.org/README.html#extension-yaml_metadata_block), the YAML metadata block can also be ended with three dots (...) instead of three hyphens. I think your remarkable plugin should support that as well : )

**Comment by jonschlinkert** [comment]
IMHO that seems like a bad idea. Why complicate parsing with a potentially ambiguous delimiter? Is there a reason that `---` doesn't work?

**Comment by vladipus** [comment]
Works, but still a standard is a standard)

**Comment by jonschlinkert** [comment]
Pandoc is not a standard. It's a library. Closing since this isn't going to be implemented here

**Comment by vladipus** [comment]
Yes and no. Every software introduces its standard either implicitly or explicitly. By partially supporting it, the project is limiting documents, already written with the `...` convention, which is not good, since people wouldn't even know what's wrong.

**Comment by jonschlinkert** [comment]
> Every software introduces its standard either implicitly or explicitly.

um, no. You're confusing conventions with standards. There is a [markdown standard](http://spec.commonmark.org/).
