### ISSUE TITLE
Dimmed Heading Attributes

### ISSUE THREAD

**Issue by vladipus** [jonschlinkert/sublime-markdown-extended#129]
That would be cool to have heading attributes (Extra syntax) be dimmed out, so they would not be so vivid as the heading itself.

Example:

![dimmed-out-heading-attribute](https://cloud.githubusercontent.com/assets/468323/16052247/07ead7e6-326c-11e6-8baf-4b8d82280a71.png)

**Comment by jonschlinkert** [comment]
Given the frequency of breaking changes being published by the current maintainers of ST, I'd prefer to be conservative with this package until we get the current bugs worked out and ST gets more stable.

**Comment by vladipus** [comment]
You might be right, by why close? Postpone maybe?)
