### ISSUE TITLE
Unit Test file for syntax highlighting

### ISSUE THREAD

**Issue by michaelblyons** [jonschlinkert/sublime-markdown-extended#132]
I think you'd have a more consistent experience with pull requests if there was a `syntax_test_*.md` file (or files) like [the one the default package has](https://raw.githubusercontent.com/sublimehq/Packages/master/Markdown/syntax_test_markdown.md) (except with more tests).

You'd need less time to check special cases, and as new special cases are identified, they can be added to the test.

**Comment by jonschlinkert** [comment]
want to do a pr?
