### ISSUE TITLE
Unpaired Backticks (`) break syntax highlighting.

### ISSUE THREAD

**Issue by bcj** [jonschlinkert/sublime-markdown-extended#133]
Unpaired backticks (`` ` ``) in a code block causes highlighting to break until an additional triple backtick is encountered.

This issue body will demonstrate the behavior when the raw text is copied into sublime.

Paired backticks:

```sh
> echo '`works`'
`works`
```

Unpaired backticks:

```sh
> echo '`'
`
```

This text is still being sh syntax highlighted.
So is this python code:

```python
> print('still sh')
still sh
```

To escape sh, an additional triple backtick is required:

```

_This_ text is markdown syntax highlighted.

```python
> print('python syntax')
python syntax
```
Here is a copyable version of that body:

    Paired backticks:

    ```sh
    > echo '`works`'
    `works`
    ```

    Unpaired backticks:

    ```sh
    > echo '`'
    `
    ```

    This text is still being sh syntax highlighted.
    So is this python code:

    ```python
    > print('still sh')
    still sh
    ```

    To escape sh, an additional triple backtick is required:

    ```

    _This_ text is markdown syntax highlighted.

    ```python
    > print('python syntax')
    python syntax
    ```

**Comment by jonschlinkert** [comment]
Is that related to this library or sublime text?

**Comment by bcj** [comment]
This is specific to this library. Sublime's built-in Markdown syntax highlighting will render this example correctly (albeit, without syntax highlighting for code blocks)

**Comment by jonschlinkert** [comment]
punting to https://github.com/jonschlinkert/sublime-markdown-extended/issues/142
