### ISSUE TITLE
No syntax highlighting on ST 3

### ISSUE THREAD

**Issue by arielelkin** [jonschlinkert/sublime-markdown-extended#134]
ST 3114
OS 10.11.5
Color Scheme: Default - Monokai
- I installed Package Control
- I installed Markdown Extended from Package Control
- I've switched the language to Markdown Extended

Result:

![image](https://cloud.githubusercontent.com/assets/1756909/16944339/523f8cd4-4da0-11e6-87ec-8be6a7810c2a.png)

I tried removing Markdown Extended through Package Control and then installing it again, quitting and reopening ST.

**Comment by jonschlinkert** [comment]
@arielelkin thanks for the docs update!
