### ISSUE TITLE
javascript syntax highlighting 

### ISSUE THREAD

**Issue by arielelkin** [jonschlinkert/sublime-markdown-extended#136]
ST 3114
OS X 10.11
Color Scheme: Monokai Extended Origin

![image](https://cloud.githubusercontent.com/assets/1756909/16952201/81b83c4a-4dc8-11e6-978a-de2821bad01e.png)

![image](https://cloud.githubusercontent.com/assets/1756909/16952223/968b5a3a-4dc8-11e6-9606-7f3c5f6932ba.png)

The problem seems to be at the last `</View>`.

Full text if you want to reproduce:

    Compare this with React's declarative way of doing things:

    ```javascript
    class Root extends Component {  
      render() {
        return (
          <ConnectivityIndicatorView />
        );
      }
    }

    class ConnectivityIndicatorView extends Component {

      componentDidMount() {
        //generate random number between 0 and 10
        //representing whether or not we're connected.
        
        var randomNumber = Math.floor(Math.random() * 10);

        if (randomNumber > 5) {
          this.setState({
            isConnected: true
          })
        } 
        else {
          this.setState({
            isConnected: false
          })
        }
      }

      constructor() {
        super()
        this.state = {
          isConnected: false
        }
      }

      render() {
        var color;
        if (this.state.isConnected) {
          color = 'green'
        }
        else {
          color = 'red'
        }
        return (
          <View style={{'backgroundColor': color, 'width': 20, 'height': 20}}>
          </View>
        )
      }
    }
    ```

    You _describe_ your UI with React, React renders it for you, and updates it for you everytime you change the state.

**Comment by jonschlinkert** [comment]
closing since jsx is not valid javascript, and I think the result you're getting is to be expected. A pr to add support for jsx would be welcome.

**Comment by arielelkin** [comment]
fair enough. 

as a workaround, setting the language to `html` does an ok job.
