### ISSUE TITLE
JSX breaks syntax highlighting till end of file

### ISSUE THREAD

**Issue by DeBaum** [jonschlinkert/sublime-markdown-extended#139]
When using JSX in js code block the syntax highlighting stops working properly till the end of file:

![image](https://cloud.githubusercontent.com/assets/11390506/18240411/df94f4fe-734b-11e6-825c-a272b0cc970b.png)

* There is a line-break right before and after the codeblock
* There are no trailing whitespaces after the start and end of the codeblock

**Comment by jonschlinkert** [comment]
see https://github.com/jonschlinkert/sublime-markdown-extended/issues/136#issuecomment-233685214
