### ISSUE TITLE
ST 3124: Error loading syntax, apparent recursion within a with_prototype action: 25000 context sanity limit hit

### ISSUE THREAD

**Issue by simonhaenisch** [jonschlinkert/sublime-markdown-extended#141]
With the latest ST release (3124), when I have the default markdown package disabled, I get an error message like in the title (also see the forum link below) and the syntax highlighting won't work.

Enabling the default markdown package fixed the problem. Is it intended to have them both enabled?

Maybe this info is related:
https://forum.sublimetext.com/t/syntax-highlighting-problem-with-3113-apparent-recursion-within-a-with-prototype-action-25000-context-sanity-limit-hit/19914/22

**Comment by jessmartin** [comment]
> Enabling the default markdown package fixed the problem. Is it intended to have them both enabled?

That also fixed it for me - thanks for the fix!

**Comment by simov** [comment]
> Enabling the default markdown package

Can you elaborate on this? I'm really not getting it. Which one is the default Markdown package and how can I enable it? I tried switching the file syntax from _Markdown Extended_ to _Markdown_ but it doesn't work.

**Comment by rbnhmll** [comment]
In your preferences>settings file you can remove or comment out **Markdown** from your **ignored_packages**. At least a temporary fix.

```
"ignored_packages":
	[
		// "Markdown",
		"Vintage"
	],
```

**Comment by simov** [comment]
Thanks @rbnhmll !

Actually adding `Markdown` to my ignored packages solved it for me :laughing: 

I mean I have this `.sublime-syntax` manually placed in my packages folder, because I have some custom stuff there. I didn't installed it with package control.

**Comment by simonhaenisch** [comment]
Well that is kind of strange now :stuck_out_tongue_winking_eye:

Actually there is only two places where `with_prototype` is used:
* [Markdown Extended.sublime-syntax#L1280](https://github.com/jonschlinkert/sublime-markdown-extended/blob/49658acf2d2ff3d7f2eaf471a0143e2284b6e223/Syntaxes/Markdown%20Extended.sublime-syntax#L1280)
* [Markdown Extended.sublime-syntax#L1304](https://github.com/jonschlinkert/sublime-markdown-extended/blob/49658acf2d2ff3d7f2eaf471a0143e2284b6e223/Syntaxes/Markdown%20Extended.sublime-syntax#L1304)

Both times `latex_elements` is included and `latex_elements` has `include: latex_elements` itself ([L1263](https://github.com/jonschlinkert/sublime-markdown-extended/blob/49658acf2d2ff3d7f2eaf471a0143e2284b6e223/Syntaxes/Markdown%20Extended.sublime-syntax#L1263)), so maybe this is where the recursion happens? I don't have any experience with syntax files :expressionless: @simov is your change related to the latex part?

**Comment by simov** [comment]
So I'm back with the same error. It turns out that my .sublime-syntax is identical, it's just not installed through the package manager.

Ignoring the Markdown package actually removes Markdown from the list of available syntaxes.

**Comment by jonschlinkert** [comment]
something changed in sublime text (again) that is causing these issues. I would be very appreciative if anyone can shed any light on what's happening

**Comment by niksy** [comment]
Same error occurs for Bash (Shell) syntax.

**Comment by simov** [comment]
Adding `ShellScript` to the list of ignored packages solves it for me. Too bad I actually want my `bash` code blocks highlighted in my markdown files. The problem is in another syntax file and just because this syntax loads other syntaxes the error manifests here.

Can someone report the issue with sublime's default `ShellScript` package on their official forum or something? They just released a hotfix today, but that doesn't seems to fix this issue.

**Comment by jonschlinkert** [comment]
@randy3k any thoughts on this? The `latex` code appears to be causing the issue. When I remove latext support, the errors go away. I wanted to get your thoughts first and see if you had a fix before I just remove latex support.

**Comment by randy3k** [comment]
The latex syntax was updated in the recent versions of ST.please remove the latex section for now. I will fix it asap

**Comment by jonschlinkert** [comment]
> please remove the latex section for now.

I'll try to do it this evening, if someone wants to do a pr before then that would be great

**Comment by lwolfsonkin** [comment]
Just pinging this issue. I was wondering if there are any updates to getting LaTex support both for math and arbitrary LaTex back in this package.

**Comment by hws-sp** [comment]
I had to remove CSS3 and HTML5 from package list

**Comment by tegendraads** [comment]
@hws-sp Thanks! That solved my problem with the same errror occurring for the CML package. Removed CSS3 and HTML5.

**Comment by tuayo77** [comment]
remove html and css 
it work for me

**Comment by skwidz** [comment]
removing css3 worked for me. thanks @hws-sp

**Comment by developer669** [comment]
Yep! 
Just remove css3 package. works for me ! 
Thanks!

**Comment by indrayam** [comment]
My setup:
MacOS Sierra 10.12.6
Sublime Text Dev Channel Build 3157

I had set MarkdownExtended as my default Syntax type for .md files.  Every time I opened a Markdown file, I would get this error:

```
Error loading syntax file "Packages/Markdown Extended/Syntaxes/MarkdownExtended.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit
```

I decided to take the advice shared above. Uninstalled the CSS3 package and the error went away!

Thanks again

**Comment by bcomnes** [comment]
Disabled CSS3 made the error go away for me.  Man, what a mess sublime text plugins have become.

**Comment by ruborg** [comment]
Same issue, removing package `JavaScriptNext - ES6 Syntax` fixed it

**Comment by FrancisBou** [comment]
Is there another way than just removing the package? I need `JavaScriptNext - ES6 Syntax` and this issue appeared out of the blue on multiple machines..

**Comment by Nemesis19** [comment]
JavaScriptNext - ES6 Syntax was my issue too

**Comment by 0xMishell** [comment]
@ruborg What if I need this package? This error happens with  JavaScriptNext for me, and I cant understand why. Previously, everything worked fine with JavaScriptNext - ES6 Syntax

**Comment by FrancisBou** [comment]
@mishell-trickster Updating Sublime Text to the latest version solved this problem for me.

**Comment by pup500** [comment]
As others have noticed, this error will appear when a **different** plugin has a problem. My problem was also with the JavaScriptNext plugin.

**Comment by rezn8d** [comment]
ditto: JavaScriptNext - ES6 Syntax removed and all clear.

**Comment by Akamaozu** [comment]
+1 `JavaScriptNext - ES6 Syntax` as source of issues.

Removed package and everything is right again.

**Comment by sergeifilippov** [comment]
+1 JavaScriptNext - ES6 Syntax as source of issues.

Removed package and everything is right again.

**Comment by blake-regalia** [comment]
For those having issues w/ `JavaScriptNext`, might be worth switching to the much cleaner `Ecmascript` package: [bathos/Ecmascript-Sublime](https://github.com/bathos/Ecmascript-Sublime).

**Comment by maparent** [comment]
Ecmascript-Sublime is also mentioning that error fyi. There is an interesting analysis of the recursion issue in https://github.com/bathos/Ecmascript-Sublime/issues/51

Incidentally, it has no support for flow, for those of us who need that.
I just discovered that https://github.com/borela/naomi who does that well, though I still run into the recursion error.

**Comment by armlesshobo** [comment]
Adding Java and Java Server Pages to the list

**Comment by hashimaziz1** [comment]
Can confirm that disabling the CSS3 package solved this error appearing when using the Markdown or MultiMarkdown syntax, but it's ridiculous that this needs to be done at all, and that this hasn't been properly fixed after 2 years. It indicates something I've suspected for a while; that the state of ST3 development is a mess, and I'm seriously considering dropping it for something like VSCode or Atom.

**Comment by armlesshobo** [comment]
Removing "Naomi" fixed  Groovy & Java syntax highlighting for me.

**Comment by ErAz7** [comment]
Thanks @armlesshobo 
disabled Naomi and now it's working
