### ISSUE TITLE
No highlighting

### ISSUE THREAD

**Issue by wzup** [jonschlinkert/sublime-markdown-extended#146]
![md - sublime text unregistered 2016-09-30 12 57 36](https://cloud.githubusercontent.com/assets/3880497/18981116/d418a604-870d-11e6-93c6-50ce42422615.png)

**Comment by wzup** [comment]
Ok, there is a typo. Should be `javascript`, with the "c". It is better to use just `js` to avoid typos in long words.

However, the plugin doesn't highlight headers
```
## H1
### H2
and so on
```

**Comment by jonschlinkert** [comment]
Did you follow the instructions in the readme and enable this as the default syntax for markdown?

**Comment by richardbuff** [comment]
I had this same problem until I followed installation instructions for this : https://github.com/jonschlinkert/sublime-monokai-extended  <-- That solved my issues

**Comment by jonschlinkert** [comment]
closing based on age
