### ISSUE TITLE
Highliting HTML Comments inside YAML Front Metter

### ISSUE THREAD

**Issue by yaitloutou** [jonschlinkert/sublime-markdown-extended#152]
The comments inside front matter header are highlighted the same as uncommented key / values. 

with **Markdown-extended**
![capture](https://cloud.githubusercontent.com/assets/12500626/21753452/8a1acd26-d5e5-11e6-9b8e-07cbf24767de.PNG)

with **Markdown** (Sublime text 3 default highlighting)
![capture2](https://cloud.githubusercontent.com/assets/12500626/21753487/557e6590-d5e6-11e6-80da-3fb3bd7bb763.PNG)

**Comment by jonschlinkert** [comment]
in front-matter, code comments should use `yaml` syntax:

```yaml
---
# this is a comment
foo: bar
---
```

However, recent changes in ST3 seem to have broken highlighting on yaml flavored comments. Let me know if they work for you, I'll be pushing up some changes soon anyway, if yaml comments are broken I can get that fixed too

**Comment by yaitloutou** [comment]
thank you, in the yaml front-matter, of my jekyll website, i'm using the html standard comments `<!-- commented stuff -->` and it was working fine with the default ST3 default markdown highlighting.

I'll test with `# comment` and let you know if it's working to, but since the default html comment are working i suppose it should be highlighted as such. 

btw, I've forked the repo and trying to play with :

```
patterns:
- name: markup.raw.yaml.front-matter
  begin: (?<!\s)---\n$
  end: ^---\s
  patterns:
  - include: source.yaml
  - include: text.html.basic
```

is this the right place to edit the code ?

**Comment by yaitloutou** [comment]
comment with `# yaml syntax`
![capture3](https://cloud.githubusercontent.com/assets/12500626/21754043/147d44b2-d5f0-11e6-8011-736ccbab6f48.PNG)

it seems both html and yaml comment syntax are not highlighted correctly.

and you can use any of them in the yaml front-matter

**Comment by jonschlinkert** [comment]
Yeah, I noticed this recently as well. It used to work, but changes in ST core have been breaking the highlighting in a number of different places.

**Comment by jonschlinkert** [comment]
closing since html comments are not valid in YAML (which is the issue  was originally created about).
