### ISSUE TITLE
Feature request: New indented style

### ISSUE THREAD

**Issue by evanmoran** [jonschlinkert/sublime-markdown-extended#182]
Hi there! 

I love this project and had an idea for you that's been tickling the back of my brain all week. Curious what you think, and if you'd consider a pull request for this :)

Here's an example that works currently to highlight Javascript:

    # Current Style
    Let's highlight this code:
    ```javascript
    var a = 5;
    ```
    Hurray, it worked!

What if this also could be written in an indented style:

    # New Indented Style
    Let's highlight this code:
        ```javascript
        var a = 5;
    Hurray, it worked!

This has couple cool benefits:

1. No triple quotes are needed at the end, because the indention serves as the region ending. 

2. The indention fits the code block quite naturally, and I think this makes the other markdown parts easier to read (paragraphs, headers, etc)

Thanks again for all the hard work!

-Evan

**Comment by jonschlinkert** [comment]
Since this doesn't follow https://commonmark.org/ standards, I'm going to go ahead and close. But I do appreciate the issue and the time you took to write it.
