### ISSUE TITLE
Higlighting the entire code block

### ISSUE THREAD

**Issue by houshuang** [jonschlinkert/sublime-markdown-extended#25]
Would it be possible to higlight the entire fenced code block, similar to what RStudio does? Even if this was just an option, or if there was an easy way to do this I could make the edit myself... I find it much cleaner to have the Markdown visually separated from the code. ![](http://reganmian.net/blog/images/2013-10-09-starting-data-analysiswrangling-with-r-things-i-wish-id-been-told_-_whole-04.png)

Thanks!

**Comment by jonschlinkert** [comment]
closing since this is something I personally would dislike.. however, I'd be happy to take a pr if someone would like to add preferences that would allow this to be enabled/disabled.
