### ISSUE TITLE
Crash inserting empty HTML element between 'bold' delimiters **

### ISSUE THREAD

**Issue by samsalisbury** [jonschlinkert/sublime-markdown-extended#29]
I'm using **Sublime Text 2.0.2, build 2221 on Windows 8.**
Markdown Extended version: **v2013.10.17.14.22.26**

Steps to reproduce:
1. Open a new tab in Sublime Text 2
2. Copy this text into the tab: `**Bold text paste inside here**`
3. Set the syntax to 'Markdown Extended'
4. Copy the following into your clipboard: `<span id='hello'></span>`
5. Paste this between 'paste' and 'inside' in the tab.
6. Observe the bug: window becomes unresponsive, Windows tells you the program is not responding.

**Comment by jonschlinkert** [comment]
closing based on age
