### ISSUE TITLE
dd in shell fenced block causes wrong highlighting

### ISSUE THREAD

**Issue by tummychow** [jonschlinkert/sublime-markdown-extended#56]
Try this with the highlighting set to `bash`:

```bash
$ dd if=/dev/zero of=swapfile bs=1M count=512
$ mkswap swapfile
```

The `if` in the dd command is interpreted as a conditional keyword, so now I guess the grammar is looking for the matching `fi`. As a result, the fenced block doesn't end at the second set of backticks (it thinks the backticks are a command substitution string). You can see GitHub's syntax highlighter is actually making the same mistake, since the `if` is bolded, but the fenced block doesn't end up consuming this entire issue, so it's not quite as bad.

Not sure if there's an easy solution to this problem. From what I know, dd's command syntax is quite specific, and doesn't allow for a space before the equals sign. Maybe that can be used to solve this issue (check for a space after `if` before interpreting it as a keyword`, but I wouldn't be surprised if that was insufficient.

**Comment by jonschlinkert** [comment]
punting to https://github.com/jonschlinkert/sublime-markdown-extended/issues/142

**Comment by molomby** [comment]
Looks like the same issue in a slightly different context:

![screen shot 2017-09-29 at 3 36 05 pm](https://user-images.githubusercontent.com/2416367/31002130-138eeeb4-a52c-11e7-9d78-1eb7d0b98bc5.png)
I'm on..

- Sublime Text v3.0 build 3142
- Markdown Extended v2017.08.08.23.08.34

Can we get this reopened?

**Comment by doowb** [comment]
@molomby #142 is opened to track this issue. I updated the comment above to point to it.
