### ISSUE TITLE
Variable underscore mistaken as emphasize

### ISSUE THREAD

**Issue by codehugger** [jonschlinkert/sublime-markdown-extended#61]
It is very common to use _ in the names of variables. Is it possible to fix it so that variables names that start with _ or use it within the variable name are not highlighted as emphasis (italic). Example

![screenshot](https://cloud.githubusercontent.com/assets/615/4009877/13240cda-29eb-11e4-9fc7-107426d86c62.png)

**Comment by pradyunsg** [comment]
Bump. Any fixes?
