### ISSUE TITLE
Ruby syntax highlighting doesnt work

### ISSUE THREAD

**Issue by fbehrens** [jonschlinkert/sublime-markdown-extended#62]
The readme does say it supports ruby syntax highlighting,
but on my sublime 3 with monokai extended theme it doesn't work.

![image](https://cloud.githubusercontent.com/assets/13704/4041918/3765e81a-2cfd-11e4-87c5-cb64b224298a.png)

**Comment by jonschlinkert** [comment]
closing based on previous comment
