### ISSUE TITLE
Problem with Java 8 "Object::new"

### ISSUE THREAD

**Issue by jeremychone** [jonschlinkert/sublime-markdown-extended#65]
Someone, doing a "::new" notation on something like "Object::new" breaks the code block. Not sure if it comes from this extension or of the java syntax parser.

```java
Object::new
```

**Comment by jonschlinkert** [comment]
I did reproduce this issue, but I think it's a problem with the java syntax highlighter. the bash highlighter has similar issues. Closing for now but we can reopen if needed
