### ISSUE TITLE
Trailing spaces

### ISSUE THREAD

**Issue by leakyMirror** [jonschlinkert/sublime-markdown-extended#67]
There are lots of trailing spaces in ```Syntaxes/Markdown Extended.JSON-tmLanguage``` file. My Sublime removes them automatically so I spent lots of time trying to understand, why ```git diff``` was showing so much edits it that file. So are those spaces left on purpose or just by accident?

**Comment by jonschlinkert** [comment]
sorry didn't see this before. that file is automatically generated.
