### ISSUE TITLE
Ignore syntax highlighting inside dollar signs

### ISSUE THREAD

**Issue by tehrengruber** [jonschlinkert/sublime-markdown-extended#69]
When writing Markdown with Mathjax content you often use single underscores inside dollar signs like

```
Some text
...
$\int_a^b f(x) dx$
...
```

It would be very nice if the syntax highlighter would recognize this since otherwise your whole content looks kinda wierd. As there is no standard format for defining equations in markdown syntax (at least what i know) i would be desirable that this would be configurable in the settings of the plugin. This is most likely a feature request and not a bug but since i'm not capable of changing this i would really appreciate it if someone could implement/fix this :-)

**Comment by jonschlinkert** [comment]
yeah, this isn't a bug. like you said it's more of a feature request, but I don't think it this plugin would/could support that. the highlighting in the fenced code blocks is provided by the highlighters for the respective languages defined for the code blocks.

**Comment by BasicXP** [comment]
Why not make dollar signs be similar to code blocks, enabling TeX/LaTeX highlighting? Would that be possible?
