### ISSUE TITLE
Doesn’t work.

### ISSUE THREAD

**Issue by dy** [jonschlinkert/sublime-markdown-extended#72]
I use ST build 3065.
I’ve installed markdown extended via package control.
I’ve restarted sublime.
Still I have (no italics, no bold):
![image](https://cloud.githubusercontent.com/assets/300067/5236260/ea8e79a6-783f-11e4-9d4d-86db25c68b4e.png)

IDK, maybe it conflicts somehow with other packages?
Tried to turn off DocBlockr, Markdown, Sublime Linter - no success.

**Comment by NQuinn27** [comment]
I did actually reproduce this, I think. It stopped working for me when I was trying to work out how to reference the tmLanguage file for settings. (I unzipped the package to see contents), then it stopped working.

I needed to remove the package, delete the Markdown Extended Caches and also removed the session file. From a fresh start I installed the package again and now it works.

I hope this helps.

ST Build 3065
