### ISSUE TITLE
Single-quote is breaking everything, but only sometimes‽

### ISSUE THREAD

**Issue by CoolOppo** [jonschlinkert/sublime-markdown-extended#73]
Here's how I discovered it:
![](http://i.imgur.com/7uXV0KV.png)

The full text for that file is [here](https://gist.github.com/CoolOppo/e61288e2fe039ce1f4c2) in case you need to try it out. I tried to make it occur in different files, but I can't figure out how to reproduce this bug!

**Comment by jonschlinkert** [comment]
it's not the single quote that's causing an issue. It's using `---`, which is the delimiter most commonly used by any library that parses front matter, like jekyll, and this library offers support for front matter highlighting. To fix the highlighting you can  use `***` or `+++` for line breaks.
