### ISSUE TITLE
Typewriter scrolling?

### ISSUE THREAD

**Issue by rsgranne** [jonschlinkert/sublime-markdown-extended#77]
Great extension, but for some reason, when I click anywhere, that line scrolls to the center of the ST window, a la typewriter scrolling. Am I correct that this is caused by this extension? If so, how do I disable it?

Tks!

**Comment by jonschlinkert** [comment]
Never heard of this happening. I can't see how this plugin would cause it. that would be frustrating for sure. I'll leave this open for a couple days to see if anyone else has experienced this from this plugin.

**Comment by rsgranne** [comment]
After I read your comment, I disabled Markdown Extended, & the problem went away. Re-enabled it, & it came back. I don’t see how your plugin could cause it either!

**Comment by rsgranne** [comment]
OK, I’ve solved it. It was the Markdown Editing plugin. I still have no idea how disabling your plugin temporarily turned off the problem, but once I edited preferences to kill typewriter scrolling, all was swell. Thanks for your willingness to help.

**Comment by jonschlinkert** [comment]
:+1: thanks for the follow up!
