### ISSUE TITLE
Negative indenting for Headings

### ISSUE THREAD

**Issue by c6y** [jonschlinkert/sublime-markdown-extended#78]
Any chance to get negative indenting for # Headings? Writer and Ulysses do this and it increases readability a great deal. Thanks!

![screen shot 2015-02-10 at 3 35 50 pm](https://cloud.githubusercontent.com/assets/1093547/6138911/91cb1f02-b13a-11e4-9851-32fe2c16f857.png)

**Comment by jonschlinkert** [comment]
I think this is beyond the scope of what this highlighter should do. Perhaps you could make a request on one of the markdown editing plugins for ST.
