### ISSUE TITLE
Doesn't highlight fenced code blocks in lists.

### ISSUE THREAD

**Issue by inetfuture** [jonschlinkert/sublime-markdown-extended#8]
This kind fenced code block doesn't get highlighted:

    - item1
    - item2

      ```js
      var t = new Date():
      ````

Could you support this? Thanks.

**Comment by JeanMertz** [comment]
@jonschlinkert I guess this was never merged/included? A pity.

**Comment by jonschlinkert** [comment]
pr is always welcome.

**Comment by jonschlinkert** [comment]
closing, but if someone wants to do a pr to add this I'd be happy to merge
