### ISSUE TITLE
Markdown breaks if you use raw HTML

### ISSUE THREAD

**Issue by bucaran** [jonschlinkert/sublime-markdown-extended#83]
I sometimes use raw HTML in markdown as it's totally valid syntax and sometimes it's just useful. But look at what Markdown Extended did to my markdown when I tried HTML as usual.

![untitled](https://cloud.githubusercontent.com/assets/8317250/7137161/5314c486-e2f2-11e4-8762-0e4dd6b12351.png)

The code after the `</img>` tag should be correctly parsed as Markdown Extended usually does.

**Comment by jonschlinkert** [comment]
The img element doesn't allow a close tag. Could that be the cause?

**Comment by bucaran** [comment]
There was a missing `</p>` tag as well. Me Fail. Thanks.
