### ISSUE TITLE
PHP syntax only working with php tags

### ISSUE THREAD

**Issue by 66beta** [jonschlinkert/sublime-markdown-extended#84]
ST3 bulid 3083
windows 7 64bit

![20150429134455](https://cloud.githubusercontent.com/assets/535237/7385332/1ebcb1dc-ee76-11e4-8caf-892aae8f4fc8.jpg)

Thanks for your good job!

**Comment by jonschlinkert** [comment]
I think that's to be expected. Even though you're only writing examples, you still will have to write valid code for the syntax highlighter to work properly.

**Comment by 66beta** [comment]
Thanks, that's make sense.
