### ISSUE TITLE
Document differences with MarkdownEditing

### ISSUE THREAD

**Issue by jmatsushita** [jonschlinkert/sublime-markdown-extended#86]
Hi there,

I was using MarkdownEditing so far, and the possibilities of Markdown Extended seem really great, but it would be great for others interested in making the switch like me, to see a comparison. In particular, apart from the possibility to switch to other Markdown flavors (like MultiMarkdown), do I loose anything else?

Cheers and thanks for the great plugin!

Jun

**Comment by jonschlinkert** [comment]
Hi, sorry for the late reply, I'm not familiar with MarkdownEditing. From time-to-time I get issues asking for comparisons with other packages. Doing comparisons of other packages is not something I'll probably ever spend time on (unless the "competing" package was the impetus for creating the library in the first place). This just seems like something that would be more valuable and objective when written by a neutral third party, and I'd rather spend time writing software than writing about it :) But I'd be happy to add a link to the readme if someone out there does take the time.
