### ISSUE TITLE
How to support HTML comment?

### ISSUE THREAD

**Issue by airysoar** [jonschlinkert/sublime-markdown-extended#92]
I use  in markdown-extended,and just show Plain Text color。But I use  in markdown，The Color will show comment color。

**Comment by jonschlinkert** [comment]
![screen shot 2015-06-05 at 9 39 31 am](https://cloud.githubusercontent.com/assets/383994/8007040/d587f54a-0b66-11e5-8311-53811258cc9e.png)

^^^
code comment

I haven't had any problems on mac or windows on a few different boxes/setups. It's probably either a different package causing an issue, or you're not actually using this package (meaning even if it's installed, sometimes ST will use the default markdown highlighting. make sure it's markdown-extended)

**Comment by airysoar** [comment]
think you.

**Comment by airysoar** [comment]
try to uninstall sublimetext,only install markdown-extended and  monokai-extended,still not working.
ps:on windows 7. 
![image](https://cloud.githubusercontent.com/assets/1035629/8019074/2f825b8c-0c6e-11e5-8943-3c8e167bbd3c.png)

![image](https://cloud.githubusercontent.com/assets/1035629/8019075/43486a44-0c6e-11e5-9ad1-26abd57ab808.png)

**Comment by jonschlinkert** [comment]
strange, I wonder what would cause that.... do you have any HTML packages installed in ST?

**Comment by airysoar** [comment]
@jonschlinkert no.I uninstall sublimetext,and delete all my config.only install markdown-extended and monokai-extended.

**Comment by donlelek** [comment]
@jonschlinkert same here OSX 10.10.3 & ST3 monokai-extended installed

**Comment by eivind88** [comment]
@jonschlinkert I'm having the same problem on OS X 10.10.5

**Comment by baurigae** [comment]
I am using ST3 build 3083 on Ubuntu 15.04 and embedded HTML is not syntax-highlighed at all in Markdown Extended - with Monokai Extended or any other colorscheme. It's a fresh install of the editor, I have no HTML addons.
